### ISSUE TITLE
ZK module not passing the tests in ios

### ISSUE THREAD

**Issue by ehsunahmadi** [p-num/react-native-libsignal-client#17]
there have been two prs for this (https://github.com/p-num/react-native-libsignal-client/pull/12, https://github.com/p-num/react-native-libsignal-client/pull/16) which just add the functions, but currently there are multiple issues with it including but not limited to: pniCiphereText not being the same when it's read from the presentationPniCiphertext, while the assertion for aci value passes.

**Comment by amirvatani** [comment]
fixed in https://github.com/p-num/react-native-libsignal-client/pull/18
